pull_request_rules:
  - name: Automatic merge for Dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=all tests passed
      - '#changes-requested-reviews-by=0'
      - label!="DO NOT MERGE"
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge
