language: scala
dist: xenial

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.rvm/gems
    - $HOME/build/api/chisel3
    - $HOME/build/api/firrtl
    - $HOME/build/api/chisel-testers
    - $HOME/build/api/treadle
    - $HOME/build/api/diagrammer

env:
  - buildDir=$HOME/build

jdk:
  - openjdk8

# The Makefile will take care of fetching submodules
git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - stage: "Website"
      name: "Latest API and sbt-microsite"
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/decrypt-keys.sh; fi
        - export PATH=${PATH}:./vendor/bundle
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.8.5
        - make -n --debug
        - make
        - make -n --debug
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi
